###Импорт библиотек

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers

###Подготовка данных

In [2]:
df_bp = pd.read_excel('/content/X_bp.xlsx')
df_nup = pd.read_excel('/content/X_nup.xlsx')

Изучение данных

In [3]:
df_bp.head() #состав данных в таблице

Unnamed: 0  Соотношение матрица-наполнитель  Плотность, кг/м3  \
0           0                         1.857143            2030.0   
1           1                         1.857143            2030.0   
2           2                         1.857143            2030.0   
3           3                         1.857143            2030.0   
4           4                         2.771331            2030.0   

   Модуль упругости, ГПа  Количество отвердителя, м.%  \
0             738.736842                        30.00   
1             738.736842                        50.00   
2             738.736842                        49.90   
3             738.736842                       129.00   
4             753.000000                       111.86   

   Содержание эпоксидных групп,%_2  Температура вспышки, С_2  \
0                        22.267857                100.000000   
1                        23.750000                284.615385   
2                        33.000000                284.615385   
3                        21.250000                300.000000   
4                        22.267857                284.615385   

   Поверхностная плотность, г/м2  Модуль упругости при растяжении, ГПа  \
0                          210.0                                  70.0   
1                          210.0                                  70.0   
2                          210.0                                  70.0   
3                          210.0                                  70.0   
4                          210.0                                  70.0   

   Прочность при растяжении, МПа  Потребление смолы, г/м2  
0                         3000.0                    220.0  
1                         3000.0                    220.0  
2                         3000.0                    220.0  
3                         3000.0                    220.0  
4                         3000.0                    220.0

In [4]:
df_bp.info() #информация о данных

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1023 entries, 0 to 1022
Data columns (total 11 columns):
 #   Column                                Non-Null Count  Dtype  
---  ------                                --------------  -----  
 0   Unnamed: 0                            1023 non-null   int64  
 1   Соотношение матрица-наполнитель       1023 non-null   float64
 2   Плотность, кг/м3                      1023 non-null   float64
 3   Модуль упругости, ГПа                 1023 non-null   float64
 4   Количество отвердителя, м.%           1023 non-null   float64
 5   Содержание эпоксидных групп,%_2       1023 non-null   float64
 6   Температура вспышки, С_2              1023 non-null   float64
 7   Поверхностная плотность, г/м2         1023 non-null   float64
 8   Модуль упругости при растяжении, ГПа  1023 non-null   float64
 9   Прочность при растяжении, МПа         1023 non-null   float64
 10  Потребление смолы, г/м2               1023 non-null   float64
dtypes: float64(10), i

In [5]:
df_bp.isna().sum() #наличие пропусков

Unnamed: 0                              0
Соотношение матрица-наполнитель         0
Плотность, кг/м3                        0
Модуль упругости, ГПа                   0
Количество отвердителя, м.%             0
Содержание эпоксидных групп,%_2         0
Температура вспышки, С_2                0
Поверхностная плотность, г/м2           0
Модуль упругости при растяжении, ГПа    0
Прочность при растяжении, МПа           0
Потребление смолы, г/м2                 0
dtype: int64

In [6]:
df_nup.head() #состав данных в таблице

Unnamed: 0  Угол нашивки, град  Шаг нашивки  Плотность нашивки
0           0                   0          4.0               57.0
1           1                   0          4.0               60.0
2           2                   0          4.0               70.0
3           3                   0          5.0               47.0
4           4                   0          5.0               57.0

In [7]:
df_nup.info() #информация о данных

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1040 entries, 0 to 1039
Data columns (total 4 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   Unnamed: 0          1040 non-null   int64  
 1   Угол нашивки, град  1040 non-null   int64  
 2   Шаг нашивки         1040 non-null   float64
 3   Плотность нашивки   1040 non-null   float64
dtypes: float64(2), int64(2)
memory usage: 32.6 KB


In [8]:
df_nup.isna().sum() #наличие пропусков

Unnamed: 0            0
Угол нашивки, град    0
Шаг нашивки           0
Плотность нашивки     0
dtype: int64

Объединение датасетов

In [9]:
df_new = pd.merge(df_bp, df_nup)

In [10]:
df_new.head()

Unnamed: 0  Соотношение матрица-наполнитель  Плотность, кг/м3  \
0           0                         1.857143            2030.0   
1           1                         1.857143            2030.0   
2           2                         1.857143            2030.0   
3           3                         1.857143            2030.0   
4           4                         2.771331            2030.0   

   Модуль упругости, ГПа  Количество отвердителя, м.%  \
0             738.736842                        30.00   
1             738.736842                        50.00   
2             738.736842                        49.90   
3             738.736842                       129.00   
4             753.000000                       111.86   

   Содержание эпоксидных групп,%_2  Температура вспышки, С_2  \
0                        22.267857                100.000000   
1                        23.750000                284.615385   
2                        33.000000                284.615385   
3                        21.250000                300.000000   
4                        22.267857                284.615385   

   Поверхностная плотность, г/м2  Модуль упругости при растяжении, ГПа  \
0                          210.0                                  70.0   
1                          210.0                                  70.0   
2                          210.0                                  70.0   
3                          210.0                                  70.0   
4                          210.0                                  70.0   

   Прочность при растяжении, МПа  Потребление смолы, г/м2  Угол нашивки, град  \
0                         3000.0                    220.0                   0   
1                         3000.0                    220.0                   0   
2                         3000.0                    220.0                   0   
3                         3000.0                    220.0                   0   
4                         3000.0                    220.0                   0   

   Шаг нашивки  Плотность нашивки  
0          4.0               57.0  
1          4.0               60.0  
2          4.0               70.0  
3          5.0               47.0  
4          5.0               57.0

In [11]:
df_new.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1023 entries, 0 to 1022
Data columns (total 14 columns):
 #   Column                                Non-Null Count  Dtype  
---  ------                                --------------  -----  
 0   Unnamed: 0                            1023 non-null   int64  
 1   Соотношение матрица-наполнитель       1023 non-null   float64
 2   Плотность, кг/м3                      1023 non-null   float64
 3   Модуль упругости, ГПа                 1023 non-null   float64
 4   Количество отвердителя, м.%           1023 non-null   float64
 5   Содержание эпоксидных групп,%_2       1023 non-null   float64
 6   Температура вспышки, С_2              1023 non-null   float64
 7   Поверхностная плотность, г/м2         1023 non-null   float64
 8   Модуль упругости при растяжении, ГПа  1023 non-null   float64
 9   Прочность при растяжении, МПа         1023 non-null   float64
 10  Потребление смолы, г/м2               1023 non-null   float64
 11  Угол нашивки, гра

In [12]:
df_new.isna().sum()

Unnamed: 0                              0
Соотношение матрица-наполнитель         0
Плотность, кг/м3                        0
Модуль упругости, ГПа                   0
Количество отвердителя, м.%             0
Содержание эпоксидных групп,%_2         0
Температура вспышки, С_2                0
Поверхностная плотность, г/м2           0
Модуль упругости при растяжении, ГПа    0
Прочность при растяжении, МПа           0
Потребление смолы, г/м2                 0
Угол нашивки, град                      0
Шаг нашивки                             0
Плотность нашивки                       0
dtype: int64

In [13]:
sns.pairplot(df_new.head(1000), diag_kind='kde')

Output hidden; open in https://colab.research.google.com to view.

In [14]:
df_new2 = df_new.drop(['Unnamed: 0'], axis=1)

In [15]:
#создаем переменные для сравнения и поиска конечных свойств материала
X = df_new2
y = df_new2

###Создание модели

In [16]:
from sklearn.model_selection import train_test_split

In [61]:
X_train_val, X_test, y_train_val, y_test = train_test_split(X, y, test_size=0.2, random_state=1) #деление на тест и трейн
X_train, X_val, y_train, y_val = train_test_split(X_train_val, y_train_val, test_size=0.3, random_state=1) #деление на трейн и валид

In [62]:
X_train.shape

(572, 13)

In [63]:
X_test.shape

(205, 13)

Линейналя регрессия

In [64]:
from sklearn.linear_model import LinearRegression
from sklearn import metrics

In [65]:
model = LinearRegression()
model.fit(X_train, y_train)

LinearRegression()

In [66]:
y_pred = model.predict(X_test)

In [67]:
df_lr = y_pred.mean(axis=0)

In [68]:
df_lr

array([   2.94287049, 1972.66910813,  724.71222433,  110.26369454,
         22.46475498,  287.39849967,  447.50512313,   72.88901883,
       2458.28173176,  218.63126455,   43.46341463,    6.71010176,
         57.25751564])

Случайный лес

In [69]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import GridSearchCV

In [70]:
rf = RandomForestRegressor()

rf.fit(X_train, y_train)
y_pred = rf.predict(X_test)

In [71]:
df_rf = y_pred.mean(axis=0)

In [72]:
df_rf

array([   2.9373947 , 1978.61937486,  723.21729686,  110.25096035,
         22.15344468,  285.279601  ,  454.67439456,   73.26084847,
       2449.56388394,  218.57689754,   43.91560976,    6.83515419,
         58.02998489])

Нейросеть

In [73]:
normalizer = tf.keras.layers.Normalization(axis=1)
normalizer.adapt(np.asarray(X).astype('float32'))
linear_model = tf.keras.Sequential([
    normalizer,
    layers.Dense(units=1)
])
linear_model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 normalization_1 (Normaliza  (None, 13)                27        
 tion)                                                           
                                                                 
 dense_1 (Dense)             (None, 1)                 14        
                                                                 
Total params: 41 (168.00 Byte)
Trainable params: 14 (56.00 Byte)
Non-trainable params: 27 (112.00 Byte)
_________________________________________________________________


In [74]:
linear_model.predict(X_train.astype(np.float32))

18/18 [==============================] - 0s 973us/step


array([[ 0.0345506 ],
       [ 2.3000665 ],
       [-0.5255871 ],
       [-1.6286418 ],
       [ 0.6685886 ],
       [ 1.3257394 ],
       [-0.45118988],
       [ 1.9585433 ],
       [-0.05292768],
       [-1.4870212 ],
       [-2.8914661 ],
       [-0.7411773 ],
       [-0.50016963],
       [-0.68929946],
       [-0.12123244],
       [ 0.02673459],
       [ 1.640755  ],
       [-0.47224775],
       [-0.7519082 ],
       [ 1.5028701 ],
       [-0.43325314],
       [ 1.5455338 ],
       [-1.3909078 ],
       [-1.1679493 ],
       [ 0.7910667 ],
       [ 1.0673276 ],
       [ 1.0399054 ],
       [-0.05585972],
       [-0.88061434],
       [ 1.3524143 ],
       [ 0.7335619 ],
       [-4.700853  ],
       [-0.34969807],
       [-0.09033173],
       [-0.30235484],
       [ 0.22407772],
       [ 0.41665155],
       [ 1.6033148 ],
       [-0.6818674 ],
       [-1.5630182 ],
       [ 1.8034189 ],
       [ 1.9108992 ],
       [ 1.4345133 ],
       [ 0.28527784],
       [-1.5592864 ],
       [ 0

In [75]:
linear_model.compile(
    optimizer=tf.optimizers.Adam(learning_rate=0.2),
    loss='mean_absolute_error')

In [76]:
model = linear_model.fit(
    X_train.astype(np.float32),
    y_train,
    epochs=100,
    verbose=1,
    validation_data=(X_val, y_val))

Epoch 1/100
18/18 [==============================] - 0s 10ms/step - loss: 498.8141 - val_loss: 496.9525
Epoch 2/100
18/18 [==============================] - 0s 3ms/step - loss: 495.8223 - val_loss: 494.4423
Epoch 3/100
18/18 [==============================] - 0s 4ms/step - loss: 493.4597 - val_loss: 492.2384
Epoch 4/100
18/18 [==============================] - 0s 4ms/step - loss: 491.3770 - val_loss: 490.1963
Epoch 5/100
18/18 [==============================] - 0s 3ms/step - loss: 489.3610 - val_loss: 488.2653
Epoch 6/100
18/18 [==============================] - 0s 2ms/step - loss: 487.5516 - val_loss: 486.5447
Epoch 7/100
18/18 [==============================] - 0s 4ms/step - loss: 485.8716 - val_loss: 484.9899
Epoch 8/100
18/18 [==============================] - 0s 3ms/step - loss: 484.3347 - val_loss: 483.4914
Epoch 9/100
18/18 [==============================] - 0s 3ms/step - loss: 482.7866 - val_loss: 481.9924
Epoch 10/100
18/18 [==============================] - 0s 2ms/step - loss

In [77]:
df_nn = y_pred.mean(axis=0)

In [78]:
df_nn

array([   2.9373947 , 1978.61937486,  723.21729686,  110.25096035,
         22.15344468,  285.279601  ,  454.67439456,   73.26084847,
       2449.56388394,  218.57689754,   43.91560976,    6.83515419,
         58.02998489])


Построение многослойного персептрона

In [79]:
from sklearn.neural_network import MLPRegressor

In [93]:
mlp_reg = MLPRegressor(hidden_layer_sizes=(100, 20),
                       max_iter = 300, activation = 'relu',
                       solver = 'adam')

In [94]:
mlp_reg.fit(X_train, y_train)

/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (300) reached and the optimization hasn't converged yet.
  warnings.warn(


MLPRegressor(hidden_layer_sizes=(100, 20), max_iter=300)

In [95]:
y_pred = mlp_reg.predict(X_test)

In [96]:
df_mlp = y_pred.mean(axis=0)

In [97]:
df_mlp

array([   4.8824709 , 1972.21082434,  724.7838782 ,  107.6201623 ,
         22.02215381,  284.69439718,  449.85159814,   69.16341284,
       2460.5269078 ,  219.58816731,   41.93474507,    8.47763676,
         58.48066841])

In [85]:
df_lr

array([   2.94287049, 1972.66910813,  724.71222433,  110.26369454,
         22.46475498,  287.39849967,  447.50512313,   72.88901883,
       2458.28173176,  218.63126455,   43.46341463,    6.71010176,
         57.25751564])

In [86]:
df_rf

array([   2.9373947 , 1978.61937486,  723.21729686,  110.25096035,
         22.15344468,  285.279601  ,  454.67439456,   73.26084847,
       2449.56388394,  218.57689754,   43.91560976,    6.83515419,
         58.02998489])

In [87]:
df_nn

array([   2.9373947 , 1978.61937486,  723.21729686,  110.25096035,
         22.15344468,  285.279601  ,  454.67439456,   73.26084847,
       2449.56388394,  218.57689754,   43.91560976,    6.83515419,
         58.02998489])